[project]

name='sep-python'
version='0.9.81'
description='A library for basic SEP IO all in python'

authors=[

    {name="Bob Clapp", email="bob@sep.stanford.edu"}
]

maintainesr=[
    "bob@sep.stanford.edu"
]
dependencies=[ 'google-cloud-storage>=1.34.0',
                'numba>=0.53',
                'generic-solver @ git+https://github.com/SEP-software/sep-python.git@3254c4c3ac445a3af584a928e0146713f59d6c05"
            ]


[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]


