[project]

name='sep-python'
version='0.9.85'
description='A library for basic SEP IO all in python'

authors=[

    {name="Bob Clapp", email="bob@sep.stanford.edu"}
]

maintainesr=[
    "bob@sep.stanford.edu"
]
dependencies=[ 'google-cloud-storage>=1.34.0',
                'numba>=0.53',
                'generic-solver @ git+https://github.com/SEP-software/python-solver.git@c85e2bc2f26f573d06c516669cabd924f196fa68'

            ]


[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]


