[project]

name='sep_python'
version='0.9.75'
description='A library for basic SEP IO all in python'

authors=[

    {name="Bob Clapp", email="bob@sep.stanford.edu"}
]

maintainesr=[
    "bob@sep.stanford.edu"
]
dependencies=[ 'google-cloud-storage>=1.34.0',
                'numba>=0.53',
                'genericSolver @ git+http://zapad.stanford.edu/bob/python-solver.git@da63c1c078d8c2ddb67468488db58fc5916fe578'
            ]


[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]


