[project]

name='sep_python'
version='0.9.63'
description='A library for basic SEP IO all in python'

authors=[

    {name="Bob Clapp", email="bob@sep.stanford.edu"}
]

maintainesr=[
    "bob@sep.stanford.edu"
]
dependencies=[ 'google-cloud-storage>=1.34.0',
                'numba>=0.53',
                'genericSolver @ git+http://zapad.stanford.edu/bob/python-solver.git@048ed56f2b9c7a9efd5032148b6eb7dcd5d26f65'
            ]


[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]


